TOPIC_HR_EVENTS = "hr.events"
TOPIC_HR_EVENTS_DLQ = "hr.events.dlq"
TOPIC_IDENTITY_USERS = "identity.users"
TOPIC_IDENTITY_LIFECYCLE = "identity.lifecycle"
TOPIC_ACCESS_ROLES = "access.roles"
TOPIC_ACCESS_PERMISSIONS = "access.permissions"
TOPIC_ACCESS_REQUESTS = "access.requests"
TOPIC_MONITOR_ALERTS = "monitor.alerts"
TOPIC_AUDIT_EVENTS = "audit.events"
TOPIC_REPORTS_NOTIFICATIONS = "reports.notifications"

ALL_TOPICS = [
    TOPIC_HR_EVENTS,
    TOPIC_HR_EVENTS_DLQ,
    TOPIC_IDENTITY_USERS,
    TOPIC_IDENTITY_LIFECYCLE,
    TOPIC_ACCESS_ROLES,
    TOPIC_ACCESS_PERMISSIONS,
    TOPIC_ACCESS_REQUESTS,
    TOPIC_MONITOR_ALERTS,
    TOPIC_AUDIT_EVENTS,
    TOPIC_REPORTS_NOTIFICATIONS,
]
